"""empty message

Revision ID: 016d5129933d
Revises: 5e6d609b0370
Create Date: 2021-03-15 15:17:27.622328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016d5129933d'
down_revision = '5e6d609b0370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phfcc_members', sa.Column('provider', sa.String(), nullable=True))
    op.drop_constraint('phfcc_members_phone_number_key', 'phfcc_members', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('phfcc_members_phone_number_key', 'phfcc_members', ['phone_number'])
    op.drop_column('phfcc_members', 'provider')
    # ### end Alembic commands ###
