"""empty message

Revision ID: 928a5f392387
Revises: a8934818cc5b
Create Date: 2021-02-27 16:39:08.505613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928a5f392387'
down_revision = 'a8934818cc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('auto_send', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('members', sa.Column('is_subscriber', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'is_subscriber')
    op.drop_table('messages')
    # ### end Alembic commands ###
